/**
 * Catálogo curado de roadmaps (baseado no roadmap.sh) para importar como trilhas
 * de aprendizado. Cada template vira um Roadmap com seus tópicos como itens de
 * checklist. Conteúdo curado dos roadmaps mais usados (não é um espelho literal
 * de todos os ~70 roadmaps do site).
 */
export interface RoadmapTemplate {
  id: string;
  name: string;
  category: string;
  description: string;
  items: string[];
}

export const ROADMAP_CATALOG: RoadmapTemplate[] = [
  {
    id: 'frontend',
    name: 'Frontend',
    category: 'Role-based',
    description: 'Trilha para se tornar desenvolvedor(a) frontend.',
    items: [
      'Internet e como a web funciona',
      'HTML semântico',
      'CSS (box model, seletores)',
      'CSS Layout: Flexbox e Grid',
      'Design responsivo',
      'JavaScript (fundamentos)',
      'DOM e eventos',
      'Git e GitHub',
      'npm e gerenciadores de pacotes',
      'Acessibilidade (a11y)',
      'SEO básico',
      'TypeScript',
      'React (ou Vue/Angular)',
      'Gerenciamento de estado',
      'Roteamento (React Router)',
      'Consumo de APIs (REST/GraphQL)',
      'TailwindCSS / CSS frameworks',
      'Build tools (Vite/Webpack)',
      'Linters e formatters (ESLint/Prettier)',
      'Testes (Vitest/Jest, Testing Library)',
      'Testes E2E (Playwright/Cypress)',
      'Performance web',
      'PWAs',
      'Segurança no frontend',
    ],
  },
  {
    id: 'backend',
    name: 'Backend',
    category: 'Role-based',
    description: 'Trilha para se tornar desenvolvedor(a) backend.',
    items: [
      'Internet, HTTP e DNS',
      'Uma linguagem (Node.js/Python/Go)',
      'Git e GitHub',
      'Bancos relacionais (PostgreSQL)',
      'Bancos NoSQL (MongoDB/Redis)',
      'ORMs',
      'APIs REST',
      'GraphQL',
      'Autenticação (JWT, OAuth)',
      'Autorização (RBAC)',
      'Cache',
      'Segurança (OWASP)',
      'Testes automatizados',
      'Filas de mensagens',
      'WebSockets',
      'Docker',
      'CI/CD',
      'Logging e monitoramento',
      'Escalabilidade',
      'Load balancing',
      'Índices e otimização de queries',
      'Migrations',
      'Microsserviços',
      'Rate limiting',
    ],
  },
  {
    id: 'devops',
    name: 'DevOps',
    category: 'Role-based',
    description: 'Trilha para se tornar engenheiro(a) DevOps.',
    items: [
      'Linux e linha de comando',
      'Shell scripting',
      'Redes (TCP/IP, DNS, HTTP)',
      'Uma linguagem (Python/Go)',
      'Servidores web (Nginx)',
      'Docker',
      'Kubernetes',
      'Infra como código (Terraform)',
      'Ansible',
      'CI/CD (GitHub Actions)',
      'Cloud (AWS/GCP/Azure)',
      'Monitoramento (Prometheus/Grafana)',
      'Logging (ELK)',
      'Gestão de segredos',
      'Serverless',
      'GitOps',
      'Service mesh',
      'Reverse proxy / Load balancer',
      'Backup e disaster recovery',
    ],
  },
  {
    id: 'fullstack',
    name: 'Full Stack',
    category: 'Role-based',
    description: 'Trilha para desenvolvedor(a) full stack.',
    items: [
      'HTML, CSS e JavaScript',
      'Git e GitHub',
      'Frontend framework (React)',
      'TypeScript',
      'Backend (Node.js/Express ou NestJS)',
      'Bancos SQL (PostgreSQL)',
      'ORMs (Prisma)',
      'APIs REST',
      'Autenticação e autorização',
      'Consumo de APIs no front',
      'Gerenciamento de estado',
      'Testes (front e back)',
      'Docker',
      'CI/CD',
      'Deploy (Vercel/Render/Fly)',
      'Cache (Redis)',
      'WebSockets',
      'Segurança básica',
      'Monitoramento',
    ],
  },
  {
    id: 'react',
    name: 'React',
    category: 'Skill-based',
    description: 'Aprofundamento em React.',
    items: [
      'JSX',
      'Componentes e Props',
      'Estado (useState)',
      'useEffect',
      'useContext',
      'useRef',
      'useMemo e useCallback',
      'useReducer',
      'Renderização condicional',
      'Listas e keys',
      'Formulários (controlados)',
      'React Router',
      'Context API',
      'State management (Zustand/Redux)',
      'Data fetching (TanStack Query)',
      'Custom Hooks',
      'Suspense e lazy',
      'Error Boundaries',
      'Performance (memo)',
      'Testes (Testing Library)',
      'Server Components / Next.js',
    ],
  },
  {
    id: 'nodejs',
    name: 'Node.js',
    category: 'Skill-based',
    description: 'Aprofundamento em Node.js.',
    items: [
      'Módulos (CommonJS e ESM)',
      'npm e package.json',
      'Event loop',
      'Assíncrono (promises, async/await)',
      'File System',
      'Streams e Buffers',
      'Módulo HTTP',
      'Express',
      'Middlewares',
      'Roteamento',
      'APIs REST',
      'Bancos (Prisma/Mongoose)',
      'Autenticação (JWT)',
      'Variáveis de ambiente',
      'Tratamento de erros',
      'Testes (Jest)',
      'Logging',
      'Worker Threads / Cluster',
      'WebSockets',
      'Deploy',
    ],
  },
  {
    id: 'javascript',
    name: 'JavaScript',
    category: 'Skill-based',
    description: 'Fundamentos e recursos modernos de JavaScript.',
    items: [
      'var, let e const',
      'Tipos de dados',
      'Operadores',
      'Funções',
      'Escopo e closures',
      'Hoisting',
      'this',
      'Arrow functions',
      'Arrays e métodos',
      'Objetos',
      'Destructuring',
      'Spread e rest',
      'Template literals',
      'Manipulação do DOM',
      'Eventos',
      'Promises',
      'async/await',
      'Fetch API',
      'ES Modules',
      'Prototypes e herança',
      'Classes',
      'Tratamento de erros',
      'JSON',
      'Event loop',
    ],
  },
  {
    id: 'typescript',
    name: 'TypeScript',
    category: 'Skill-based',
    description: 'Aprofundamento em TypeScript.',
    items: [
      'Tipos básicos',
      'Interfaces',
      'Type aliases',
      'Union e intersection',
      'Generics',
      'Enums',
      'Tuplas',
      'Inferência de tipos',
      'Type narrowing',
      'Type guards',
      'Utility types (Partial, Pick, Omit, Record)',
      'keyof e typeof',
      'Mapped types',
      'Conditional types',
      'Módulos',
      'Declaration files (.d.ts)',
      'tsconfig',
      'Discriminated unions',
      'Decorators',
    ],
  },
  {
    id: 'python',
    name: 'Python',
    category: 'Skill-based',
    description: 'Fundamentos de Python.',
    items: [
      'Sintaxe e variáveis',
      'Tipos de dados',
      'Operadores',
      'Controle de fluxo (if/for/while)',
      'Funções',
      'Listas, tuplas, sets e dicts',
      'Comprehensions',
      'Strings',
      'Leitura/escrita de arquivos',
      'Módulos e pacotes',
      'pip e venv',
      'Exceções',
      'POO (classes)',
      'Decorators',
      'Generators',
      'Lambda',
      'Type hints',
      'Testes (pytest)',
      'Async (asyncio)',
      'Bibliotecas (requests, pandas, numpy)',
    ],
  },
  {
    id: 'system-design',
    name: 'System Design',
    category: 'Skill-based',
    description: 'Fundamentos de projeto de sistemas escaláveis.',
    items: [
      'Escalabilidade (horizontal/vertical)',
      'Latência vs throughput',
      'Load balancing',
      'Cache (Redis, CDN)',
      'SQL vs NoSQL',
      'Sharding',
      'Replicação',
      'Teorema CAP',
      'Modelos de consistência',
      'Filas de mensagens (Kafka)',
      'Rate limiting',
      'Design de APIs',
      'Monolito vs microsserviços',
      'Proxy e reverse proxy',
      'Consistent hashing',
      'Índices e particionamento',
      'Disponibilidade e tolerância a falhas',
      'Monitoramento',
    ],
  },
  {
    id: 'docker',
    name: 'Docker',
    category: 'Skill-based',
    description: 'Containers com Docker.',
    items: [
      'Containers vs VMs',
      'Imagens',
      'Dockerfile',
      'Layers e cache',
      'docker build e run',
      'Volumes',
      'Redes',
      'Docker Compose',
      'Registries (Docker Hub)',
      'Variáveis de ambiente',
      'Multi-stage builds',
      'Ciclo de vida do container',
      'Mapeamento de portas',
      'Health checks',
      'Boas práticas',
      'Segurança',
    ],
  },
  {
    id: 'kubernetes',
    name: 'Kubernetes',
    category: 'Skill-based',
    description: 'Orquestração de containers com Kubernetes.',
    items: [
      'Pods',
      'Nodes e Clusters',
      'Deployments',
      'ReplicaSets',
      'Services',
      'Ingress',
      'ConfigMaps',
      'Secrets',
      'Volumes e PersistentVolumes',
      'Namespaces',
      'kubectl',
      'Labels e selectors',
      'Helm',
      'StatefulSets',
      'Jobs e CronJobs',
      'Autoscaling (HPA)',
      'RBAC',
      'Monitoramento',
    ],
  },
  {
    id: 'sql',
    name: 'SQL / PostgreSQL',
    category: 'Skill-based',
    description: 'Banco de dados relacional e SQL.',
    items: [
      'SELECT e WHERE',
      'ORDER BY e LIMIT',
      'JOINs (INNER/LEFT/RIGHT)',
      'GROUP BY e agregações',
      'HAVING',
      'Subqueries',
      'INSERT, UPDATE, DELETE',
      'Constraints (PK, FK, UNIQUE)',
      'Índices',
      'Transações e ACID',
      'Views',
      'CTEs (WITH)',
      'Window functions',
      'Normalização',
      'Tipos de dados',
      'Design de schema',
      'Stored procedures e triggers',
      'EXPLAIN e otimização',
    ],
  },
  {
    id: 'git',
    name: 'Git e GitHub',
    category: 'Skill-based',
    description: 'Controle de versão com Git e GitHub.',
    items: [
      'init e clone',
      'add e commit',
      'status e log',
      'Branches',
      'Merge',
      'Rebase',
      'Remotes',
      'push, pull e fetch',
      '.gitignore',
      'Stash',
      'Tags',
      'reset e revert',
      'cherry-pick',
      'Resolução de conflitos',
      'Pull Requests',
      'Forks',
      'Code review',
      'GitHub Actions',
      'Git Flow',
    ],
  },
  {
    id: 'dsa',
    name: 'Estruturas de Dados e Algoritmos',
    category: 'Skill-based',
    description: 'DSA para entrevistas e fundamentos.',
    items: [
      'Notação Big-O',
      'Arrays',
      'Strings',
      'Listas ligadas',
      'Pilhas',
      'Filas',
      'Hash tables',
      'Árvores (BST)',
      'Heaps',
      'Grafos',
      'Recursão',
      'Ordenação (quick, merge)',
      'Busca binária',
      'Two pointers',
      'Sliding window',
      'BFS e DFS',
      'Programação dinâmica',
      'Greedy',
      'Backtracking',
      'Tries',
    ],
  },
  {
    id: 'go',
    name: 'Go',
    category: 'Skill-based',
    description: 'Fundamentos da linguagem Go.',
    items: [
      'Sintaxe e variáveis',
      'Tipos de dados',
      'Funções',
      'Pacotes e módulos',
      'Structs',
      'Interfaces',
      'Ponteiros',
      'Slices e maps',
      'Goroutines',
      'Channels',
      'Concorrência (sync, WaitGroup)',
      'Tratamento de erros',
      'defer, panic e recover',
      'Standard library',
      'Testes',
      'Servidor HTTP',
      'JSON',
      'Generics',
      'Context',
    ],
  },
];
