/**
 * Catálogo curado de roadmaps (baseado no roadmap.sh) — guias completos com
 * descrição e links reais (docs oficiais, MDN, roadmap.sh) em cada tópico.
 *
 * São navegáveis direto na tela (pré-definidos) e importáveis para virar uma
 * trilha com checklist de progresso. Conteúdo curado dos roadmaps mais usados.
 */
export interface CatalogLink {
  label: string;
  url: string;
}

export interface CatalogItem {
  title: string;
  description?: string;
  links?: CatalogLink[];
}

export interface RoadmapTemplate {
  id: string;
  name: string;
  category: string;
  description: string;
  /** Página oficial do roadmap no roadmap.sh. */
  url: string;
  items: CatalogItem[];
}

const mdn = (path: string): CatalogLink => ({
  label: 'MDN',
  url: `https://developer.mozilla.org/pt-BR/docs/${path}`,
});

export const ROADMAP_CATALOG: RoadmapTemplate[] = [
  {
    id: 'frontend',
    name: 'Frontend',
    category: 'Role-based',
    description: 'Guia completo para se tornar desenvolvedor(a) frontend.',
    url: 'https://roadmap.sh/frontend',
    items: [
      {
        title: 'Como a internet funciona',
        description:
          'Entenda HTTP, DNS, navegadores, hospedagem e como uma página chega até o usuário.',
        links: [mdn('Web/HTTP/Overview'), { label: 'roadmap.sh', url: 'https://roadmap.sh/frontend' }],
      },
      {
        title: 'HTML semântico',
        description:
          'Estrutura de páginas com tags semânticas, formulários e acessibilidade básica.',
        links: [mdn('Web/HTML'), { label: 'HTML semântico (MDN)', url: 'https://developer.mozilla.org/pt-BR/docs/Glossary/Semantics' }],
      },
      {
        title: 'CSS: fundamentos',
        description: 'Seletores, box model, cores, tipografia e especificidade.',
        links: [mdn('Web/CSS')],
      },
      {
        title: 'CSS Layout: Flexbox e Grid',
        description: 'Layouts modernos e responsivos com Flexbox e CSS Grid.',
        links: [
          { label: 'A Complete Guide to Flexbox', url: 'https://css-tricks.com/snippets/css/a-guide-to-flexbox/' },
          { label: 'A Complete Guide to Grid', url: 'https://css-tricks.com/snippets/css/complete-guide-grid/' },
        ],
      },
      {
        title: 'Design responsivo',
        description: 'Media queries, unidades relativas e mobile-first.',
        links: [mdn('Web/CSS/CSS_media_queries/Using_media_queries')],
      },
      {
        title: 'JavaScript (fundamentos)',
        description: 'Sintaxe, tipos, funções, objetos, DOM e assíncrono.',
        links: [mdn('Web/JavaScript'), { label: 'javascript.info', url: 'https://javascript.info/' }],
      },
      {
        title: 'DOM e eventos',
        description: 'Manipular a árvore do documento e responder a eventos.',
        links: [mdn('Web/API/Document_Object_Model')],
      },
      {
        title: 'Git e GitHub',
        description: 'Controle de versão, branches, PRs e colaboração.',
        links: [{ label: 'Pro Git (livro)', url: 'https://git-scm.com/book/pt-br/v2' }],
      },
      {
        title: 'npm e gerenciadores de pacotes',
        description: 'Instalar dependências, scripts e versionamento (npm, pnpm, yarn).',
        links: [{ label: 'npm docs', url: 'https://docs.npmjs.com/' }],
      },
      {
        title: 'Acessibilidade (a11y)',
        description: 'ARIA, contraste, navegação por teclado e leitores de tela.',
        links: [mdn('Web/Accessibility'), { label: 'WCAG', url: 'https://www.w3.org/WAI/standards-guidelines/wcag/' }],
      },
      {
        title: 'SEO básico',
        description: 'Meta tags, semântica, performance e boas práticas.',
        links: [{ label: 'Google Search Central', url: 'https://developers.google.com/search/docs' }],
      },
      {
        title: 'TypeScript',
        description: 'JavaScript tipado — tipos, interfaces e generics.',
        links: [{ label: 'TypeScript Handbook', url: 'https://www.typescriptlang.org/docs/handbook/intro.html' }],
      },
      {
        title: 'React (ou Vue/Angular)',
        description: 'Biblioteca/framework de UI baseada em componentes.',
        links: [{ label: 'react.dev', url: 'https://react.dev/learn' }],
      },
      {
        title: 'Gerenciamento de estado',
        description: 'Context, Zustand, Redux — compartilhar estado na aplicação.',
        links: [{ label: 'Zustand', url: 'https://zustand.docs.pmnd.rs/' }],
      },
      {
        title: 'Roteamento',
        description: 'Navegação SPA com React Router (ou equivalente).',
        links: [{ label: 'React Router', url: 'https://reactrouter.com/' }],
      },
      {
        title: 'Consumo de APIs (REST/GraphQL)',
        description: 'Fetch, TanStack Query, cache e estados de carregamento.',
        links: [{ label: 'TanStack Query', url: 'https://tanstack.com/query/latest' }, mdn('Web/API/Fetch_API')],
      },
      {
        title: 'CSS frameworks (TailwindCSS)',
        description: 'Estilização utilitária e design systems.',
        links: [{ label: 'Tailwind CSS', url: 'https://tailwindcss.com/docs' }],
      },
      {
        title: 'Build tools (Vite)',
        description: 'Bundlers e dev servers modernos.',
        links: [{ label: 'Vite', url: 'https://vitejs.dev/guide/' }],
      },
      {
        title: 'Linters e formatters',
        description: 'ESLint e Prettier para qualidade e consistência.',
        links: [{ label: 'ESLint', url: 'https://eslint.org/docs/latest/' }, { label: 'Prettier', url: 'https://prettier.io/docs/en/' }],
      },
      {
        title: 'Testes (Vitest/Jest + Testing Library)',
        description: 'Testes unitários e de componentes.',
        links: [{ label: 'Testing Library', url: 'https://testing-library.com/docs/' }, { label: 'Vitest', url: 'https://vitest.dev/' }],
      },
      {
        title: 'Testes E2E (Playwright/Cypress)',
        description: 'Testes ponta a ponta simulando o usuário.',
        links: [{ label: 'Playwright', url: 'https://playwright.dev/' }],
      },
      {
        title: 'Performance web',
        description: 'Core Web Vitals, lazy loading, code-splitting e cache.',
        links: [{ label: 'web.dev/performance', url: 'https://web.dev/explore/fast' }],
      },
      {
        title: 'PWAs',
        description: 'Service workers, manifest e apps instaláveis.',
        links: [mdn('Web/Progressive_web_apps')],
      },
      {
        title: 'Segurança no frontend',
        description: 'XSS, CSRF, CORS e boas práticas.',
        links: [mdn('Web/Security')],
      },
    ],
  },
  {
    id: 'backend',
    name: 'Backend',
    category: 'Role-based',
    description: 'Guia completo para se tornar desenvolvedor(a) backend.',
    url: 'https://roadmap.sh/backend',
    items: [
      { title: 'Internet, HTTP e DNS', description: 'Como clientes e servidores se comunicam.', links: [mdn('Web/HTTP')] },
      { title: 'Uma linguagem de backend', description: 'Node.js, Python, Go, Java — escolha e domine uma.', links: [{ label: 'Node.js', url: 'https://nodejs.org/en/learn' }] },
      { title: 'Git e GitHub', description: 'Controle de versão e colaboração.', links: [{ label: 'Pro Git', url: 'https://git-scm.com/book/pt-br/v2' }] },
      { title: 'Bancos relacionais (PostgreSQL)', description: 'Modelagem, SQL e relacionamentos.', links: [{ label: 'PostgreSQL Tutorial', url: 'https://www.postgresql.org/docs/current/tutorial.html' }] },
      { title: 'Bancos NoSQL', description: 'MongoDB, Redis — documentos e chave-valor.', links: [{ label: 'MongoDB', url: 'https://www.mongodb.com/docs/manual/' }, { label: 'Redis', url: 'https://redis.io/docs/latest/' }] },
      { title: 'ORMs', description: 'Prisma, TypeORM, Sequelize — mapeamento objeto-relacional.', links: [{ label: 'Prisma', url: 'https://www.prisma.io/docs' }] },
      { title: 'APIs REST', description: 'Verbos HTTP, status codes e design de recursos.', links: [{ label: 'REST (MDN Glossary)', url: 'https://developer.mozilla.org/pt-BR/docs/Glossary/REST' }] },
      { title: 'GraphQL', description: 'Consultas flexíveis com um único endpoint.', links: [{ label: 'graphql.org', url: 'https://graphql.org/learn/' }] },
      { title: 'Autenticação (JWT, OAuth)', description: 'Identidade, tokens e login social.', links: [{ label: 'jwt.io', url: 'https://jwt.io/introduction' }, { label: 'OAuth 2.0', url: 'https://oauth.net/2/' }] },
      { title: 'Autorização (RBAC)', description: 'Controle de acesso por papéis e permissões.' },
      { title: 'Cache', description: 'Redis, cache HTTP e invalidação.', links: [{ label: 'Redis', url: 'https://redis.io/docs/latest/' }] },
      { title: 'Segurança web (OWASP)', description: 'Top 10 de vulnerabilidades e mitigação.', links: [{ label: 'OWASP Top 10', url: 'https://owasp.org/www-project-top-ten/' }] },
      { title: 'Testes automatizados', description: 'Unitários, integração e mocks.', links: [{ label: 'Jest', url: 'https://jestjs.io/docs/getting-started' }] },
      { title: 'Filas de mensagens', description: 'RabbitMQ, Kafka — processamento assíncrono.', links: [{ label: 'RabbitMQ', url: 'https://www.rabbitmq.com/tutorials' }] },
      { title: 'WebSockets', description: 'Comunicação em tempo real.', links: [mdn('Web/API/WebSockets_API')] },
      { title: 'Docker', description: 'Empacotar a aplicação em containers.', links: [{ label: 'Docker docs', url: 'https://docs.docker.com/get-started/' }] },
      { title: 'CI/CD', description: 'Integração e entrega contínua.', links: [{ label: 'GitHub Actions', url: 'https://docs.github.com/actions' }] },
      { title: 'Logging e monitoramento', description: 'Observabilidade, métricas e alertas.', links: [{ label: 'Prometheus', url: 'https://prometheus.io/docs/introduction/overview/' }] },
      { title: 'Escalabilidade', description: 'Horizontal vs vertical, statelessness.' },
      { title: 'Índices e otimização de queries', description: 'EXPLAIN, índices e performance de banco.', links: [{ label: 'PostgreSQL EXPLAIN', url: 'https://www.postgresql.org/docs/current/using-explain.html' }] },
      { title: 'Migrations', description: 'Versionamento de schema do banco.', links: [{ label: 'Prisma Migrate', url: 'https://www.prisma.io/docs/orm/prisma-migrate' }] },
      { title: 'Microsserviços', description: 'Arquitetura distribuída e comunicação entre serviços.', links: [{ label: 'roadmap.sh', url: 'https://roadmap.sh/backend' }] },
    ],
  },
  {
    id: 'devops',
    name: 'DevOps',
    category: 'Role-based',
    description: 'Guia completo para se tornar engenheiro(a) DevOps.',
    url: 'https://roadmap.sh/devops',
    items: [
      { title: 'Linux e linha de comando', description: 'Shell, permissões, processos e sistema de arquivos.', links: [{ label: 'Linux Journey', url: 'https://linuxjourney.com/' }] },
      { title: 'Shell scripting', description: 'Automação com Bash.', links: [{ label: 'Bash Guide', url: 'https://mywiki.wooledge.org/BashGuide' }] },
      { title: 'Redes (TCP/IP, DNS, HTTP)', description: 'Fundamentos de rede.', links: [mdn('Web/HTTP')] },
      { title: 'Uma linguagem (Python/Go)', description: 'Automação e ferramentas.', links: [{ label: 'Go', url: 'https://go.dev/learn/' }] },
      { title: 'Servidores web (Nginx)', description: 'Proxy reverso, TLS e balanceamento.', links: [{ label: 'Nginx docs', url: 'https://nginx.org/en/docs/' }] },
      { title: 'Docker', description: 'Containers e imagens.', links: [{ label: 'Docker docs', url: 'https://docs.docker.com/get-started/' }] },
      { title: 'Kubernetes', description: 'Orquestração de containers.', links: [{ label: 'kubernetes.io', url: 'https://kubernetes.io/docs/home/' }] },
      { title: 'Infra como código (Terraform)', description: 'Provisionar infraestrutura declarativa.', links: [{ label: 'Terraform', url: 'https://developer.hashicorp.com/terraform/docs' }] },
      { title: 'Ansible', description: 'Gerência de configuração.', links: [{ label: 'Ansible docs', url: 'https://docs.ansible.com/' }] },
      { title: 'CI/CD (GitHub Actions)', description: 'Pipelines de build, teste e deploy.', links: [{ label: 'GitHub Actions', url: 'https://docs.github.com/actions' }] },
      { title: 'Cloud (AWS/GCP/Azure)', description: 'Serviços de computação, storage e rede.', links: [{ label: 'AWS docs', url: 'https://docs.aws.amazon.com/' }] },
      { title: 'Monitoramento (Prometheus/Grafana)', description: 'Métricas, dashboards e alertas.', links: [{ label: 'Grafana', url: 'https://grafana.com/docs/' }] },
      { title: 'Logging (ELK)', description: 'Centralização e análise de logs.', links: [{ label: 'Elastic', url: 'https://www.elastic.co/guide/index.html' }] },
      { title: 'Gestão de segredos', description: 'Vault, variáveis de ambiente seguras.', links: [{ label: 'Vault', url: 'https://developer.hashicorp.com/vault/docs' }] },
      { title: 'Serverless', description: 'Funções sob demanda (Lambda, Cloud Functions).', links: [{ label: 'AWS Lambda', url: 'https://docs.aws.amazon.com/lambda/' }] },
      { title: 'GitOps', description: 'Infra e deploy dirigidos por Git (ArgoCD).', links: [{ label: 'Argo CD', url: 'https://argo-cd.readthedocs.io/' }] },
      { title: 'Reverse proxy / Load balancer', description: 'Distribuição de tráfego.', links: [{ label: 'Nginx', url: 'https://nginx.org/en/docs/' }] },
      { title: 'Backup e disaster recovery', description: 'Estratégias de recuperação.' },
    ],
  },
  {
    id: 'fullstack',
    name: 'Full Stack',
    category: 'Role-based',
    description: 'Guia completo para desenvolvedor(a) full stack.',
    url: 'https://roadmap.sh/full-stack',
    items: [
      { title: 'HTML, CSS e JavaScript', description: 'Base do frontend.', links: [mdn('Web/HTML'), mdn('Web/CSS')] },
      { title: 'Git e GitHub', description: 'Controle de versão.', links: [{ label: 'Pro Git', url: 'https://git-scm.com/book/pt-br/v2' }] },
      { title: 'Frontend framework (React)', description: 'UI baseada em componentes.', links: [{ label: 'react.dev', url: 'https://react.dev/learn' }] },
      { title: 'TypeScript', description: 'JavaScript tipado.', links: [{ label: 'TS Handbook', url: 'https://www.typescriptlang.org/docs/handbook/intro.html' }] },
      { title: 'Backend (Node/Express ou NestJS)', description: 'APIs e lógica de servidor.', links: [{ label: 'NestJS', url: 'https://docs.nestjs.com/' }] },
      { title: 'Bancos SQL (PostgreSQL)', description: 'Persistência relacional.', links: [{ label: 'PostgreSQL', url: 'https://www.postgresql.org/docs/current/tutorial.html' }] },
      { title: 'ORMs (Prisma)', description: 'Acesso a dados tipado.', links: [{ label: 'Prisma', url: 'https://www.prisma.io/docs' }] },
      { title: 'APIs REST', description: 'Design de endpoints.' },
      { title: 'Autenticação e autorização', description: 'JWT, OAuth, RBAC.', links: [{ label: 'jwt.io', url: 'https://jwt.io/introduction' }] },
      { title: 'Consumo de APIs no front', description: 'TanStack Query e cache.', links: [{ label: 'TanStack Query', url: 'https://tanstack.com/query/latest' }] },
      { title: 'Gerenciamento de estado', description: 'Context, Zustand, Redux.' },
      { title: 'Testes (front e back)', description: 'Unitários, integração e E2E.' },
      { title: 'Docker', description: 'Containerizar a stack.', links: [{ label: 'Docker', url: 'https://docs.docker.com/get-started/' }] },
      { title: 'CI/CD e deploy', description: 'Pipelines e publicação (Vercel/Render).', links: [{ label: 'GitHub Actions', url: 'https://docs.github.com/actions' }] },
      { title: 'Cache (Redis)', description: 'Reduzir latência.', links: [{ label: 'Redis', url: 'https://redis.io/docs/latest/' }] },
      { title: 'WebSockets', description: 'Tempo real.', links: [mdn('Web/API/WebSockets_API')] },
      { title: 'Segurança e monitoramento', description: 'OWASP, logs e métricas.', links: [{ label: 'OWASP Top 10', url: 'https://owasp.org/www-project-top-ten/' }] },
    ],
  },
  {
    id: 'react',
    name: 'React',
    category: 'Skill-based',
    description: 'Guia completo de React.',
    url: 'https://roadmap.sh/react',
    items: [
      { title: 'JSX', description: 'Sintaxe que mistura marcação e JavaScript.', links: [{ label: 'react.dev — JSX', url: 'https://react.dev/learn/writing-markup-with-jsx' }] },
      { title: 'Componentes e Props', description: 'Blocos reutilizáveis e passagem de dados.', links: [{ label: 'react.dev', url: 'https://react.dev/learn/passing-props-to-a-component' }] },
      { title: 'Estado (useState)', description: 'Estado local de componentes.', links: [{ label: 'useState', url: 'https://react.dev/reference/react/useState' }] },
      { title: 'useEffect', description: 'Efeitos colaterais e sincronização.', links: [{ label: 'useEffect', url: 'https://react.dev/reference/react/useEffect' }] },
      { title: 'useContext', description: 'Compartilhar dados sem prop drilling.', links: [{ label: 'useContext', url: 'https://react.dev/reference/react/useContext' }] },
      { title: 'useRef', description: 'Referências a elementos e valores mutáveis.', links: [{ label: 'useRef', url: 'https://react.dev/reference/react/useRef' }] },
      { title: 'useMemo e useCallback', description: 'Memoização para performance.', links: [{ label: 'useMemo', url: 'https://react.dev/reference/react/useMemo' }] },
      { title: 'useReducer', description: 'Estado complexo com reducers.', links: [{ label: 'useReducer', url: 'https://react.dev/reference/react/useReducer' }] },
      { title: 'Renderização condicional', description: 'Mostrar UI conforme o estado.', links: [{ label: 'react.dev', url: 'https://react.dev/learn/conditional-rendering' }] },
      { title: 'Listas e keys', description: 'Renderizar coleções com keys estáveis.', links: [{ label: 'react.dev', url: 'https://react.dev/learn/rendering-lists' }] },
      { title: 'Formulários', description: 'Inputs controlados e não controlados.', links: [{ label: 'react.dev', url: 'https://react.dev/reference/react-dom/components/input' }] },
      { title: 'React Router', description: 'Roteamento em SPAs.', links: [{ label: 'React Router', url: 'https://reactrouter.com/' }] },
      { title: 'State management', description: 'Zustand, Redux, Jotai.', links: [{ label: 'Zustand', url: 'https://zustand.docs.pmnd.rs/' }] },
      { title: 'Data fetching (TanStack Query)', description: 'Cache e sincronização de servidor.', links: [{ label: 'TanStack Query', url: 'https://tanstack.com/query/latest' }] },
      { title: 'Custom Hooks', description: 'Reutilizar lógica com hooks próprios.', links: [{ label: 'react.dev', url: 'https://react.dev/learn/reusing-logic-with-custom-hooks' }] },
      { title: 'Suspense e lazy', description: 'Carregamento assíncrono e code-splitting.', links: [{ label: 'lazy', url: 'https://react.dev/reference/react/lazy' }] },
      { title: 'Error Boundaries', description: 'Capturar erros de renderização.', links: [{ label: 'react.dev', url: 'https://react.dev/reference/react/Component#catching-rendering-errors-with-an-error-boundary' }] },
      { title: 'Performance (memo)', description: 'Evitar re-renders desnecessários.', links: [{ label: 'memo', url: 'https://react.dev/reference/react/memo' }] },
      { title: 'Testes (Testing Library)', description: 'Testar componentes como o usuário.', links: [{ label: 'RTL', url: 'https://testing-library.com/docs/react-testing-library/intro/' }] },
      { title: 'Next.js / Server Components', description: 'SSR, RSC e frameworks React.', links: [{ label: 'Next.js', url: 'https://nextjs.org/docs' }] },
    ],
  },
  {
    id: 'nodejs',
    name: 'Node.js',
    category: 'Skill-based',
    description: 'Guia completo de Node.js.',
    url: 'https://roadmap.sh/nodejs',
    items: [
      { title: 'Módulos (CommonJS e ESM)', description: 'require vs import/export.', links: [{ label: 'Node.js modules', url: 'https://nodejs.org/api/modules.html' }] },
      { title: 'npm e package.json', description: 'Dependências e scripts.', links: [{ label: 'npm docs', url: 'https://docs.npmjs.com/' }] },
      { title: 'Event loop', description: 'Como o Node executa código assíncrono.', links: [{ label: 'Event Loop', url: 'https://nodejs.org/en/learn/asynchronous-work/event-loop-timers-and-nexttick' }] },
      { title: 'Assíncrono (promises, async/await)', description: 'Fluxos não bloqueantes.', links: [mdn('Web/JavaScript/Reference/Statements/async_function')] },
      { title: 'File System', description: 'Ler e escrever arquivos.', links: [{ label: 'fs', url: 'https://nodejs.org/api/fs.html' }] },
      { title: 'Streams e Buffers', description: 'Processar dados em fluxo.', links: [{ label: 'Streams', url: 'https://nodejs.org/api/stream.html' }] },
      { title: 'Módulo HTTP', description: 'Criar servidores HTTP.', links: [{ label: 'http', url: 'https://nodejs.org/api/http.html' }] },
      { title: 'Express', description: 'Framework web minimalista.', links: [{ label: 'Express', url: 'https://expressjs.com/pt-br/' }] },
      { title: 'Middlewares', description: 'Interceptar requisições/respostas.', links: [{ label: 'Express middleware', url: 'https://expressjs.com/en/guide/using-middleware.html' }] },
      { title: 'APIs REST', description: 'Rotas, controllers e status codes.' },
      { title: 'Bancos (Prisma/Mongoose)', description: 'Persistência de dados.', links: [{ label: 'Prisma', url: 'https://www.prisma.io/docs' }] },
      { title: 'Autenticação (JWT)', description: 'Tokens e sessões.', links: [{ label: 'jwt.io', url: 'https://jwt.io/introduction' }] },
      { title: 'Variáveis de ambiente', description: 'Configuração com dotenv.', links: [{ label: 'dotenv', url: 'https://www.npmjs.com/package/dotenv' }] },
      { title: 'Tratamento de erros', description: 'Erros síncronos e assíncronos.' },
      { title: 'Testes (Jest/Vitest)', description: 'Testes automatizados.', links: [{ label: 'Jest', url: 'https://jestjs.io/' }] },
      { title: 'Worker Threads / Cluster', description: 'Paralelismo e múltiplos processos.', links: [{ label: 'Worker Threads', url: 'https://nodejs.org/api/worker_threads.html' }] },
      { title: 'WebSockets', description: 'Tempo real com ws/socket.io.', links: [{ label: 'ws', url: 'https://github.com/websockets/ws' }] },
      { title: 'Deploy', description: 'Publicar em Render/Fly/Vercel.' },
    ],
  },
  {
    id: 'javascript',
    name: 'JavaScript',
    category: 'Skill-based',
    description: 'Fundamentos e recursos modernos de JavaScript.',
    url: 'https://roadmap.sh/javascript',
    items: [
      { title: 'var, let e const', description: 'Declaração de variáveis e escopo.', links: [mdn('Web/JavaScript/Reference/Statements/let')] },
      { title: 'Tipos de dados', description: 'Primitivos e objetos.', links: [mdn('Web/JavaScript/Data_structures')] },
      { title: 'Operadores', description: 'Aritméticos, lógicos e de comparação.' },
      { title: 'Funções', description: 'Declaração, expressão e parâmetros.', links: [mdn('Web/JavaScript/Guide/Functions')] },
      { title: 'Escopo e closures', description: 'Como variáveis são acessadas.', links: [mdn('Web/JavaScript/Closures')] },
      { title: 'Hoisting', description: 'Elevação de declarações.', links: [mdn('Glossary/Hoisting')] },
      { title: 'this', description: 'Contexto de execução.', links: [mdn('Web/JavaScript/Reference/Operators/this')] },
      { title: 'Arrow functions', description: 'Sintaxe curta e this léxico.', links: [mdn('Web/JavaScript/Reference/Functions/Arrow_functions')] },
      { title: 'Arrays e métodos', description: 'map, filter, reduce e afins.', links: [mdn('Web/JavaScript/Reference/Global_Objects/Array')] },
      { title: 'Objetos', description: 'Propriedades, métodos e prototype.', links: [mdn('Web/JavaScript/Reference/Global_Objects/Object')] },
      { title: 'Destructuring', description: 'Extrair valores de arrays/objetos.', links: [mdn('Web/JavaScript/Reference/Operators/Destructuring_assignment')] },
      { title: 'Spread e rest', description: 'Espalhar e agrupar valores.', links: [mdn('Web/JavaScript/Reference/Operators/Spread_syntax')] },
      { title: 'Template literals', description: 'Strings com interpolação.', links: [mdn('Web/JavaScript/Reference/Template_literals')] },
      { title: 'Promises', description: 'Operações assíncronas.', links: [mdn('Web/JavaScript/Reference/Global_Objects/Promise')] },
      { title: 'async/await', description: 'Assíncrono com sintaxe síncrona.', links: [mdn('Web/JavaScript/Reference/Statements/async_function')] },
      { title: 'Fetch API', description: 'Requisições HTTP no navegador.', links: [mdn('Web/API/Fetch_API')] },
      { title: 'ES Modules', description: 'import/export.', links: [mdn('Web/JavaScript/Guide/Modules')] },
      { title: 'Prototypes e herança', description: 'Cadeia de protótipos.', links: [mdn('Web/JavaScript/Inheritance_and_the_prototype_chain')] },
      { title: 'Classes', description: 'Açúcar sintático sobre prototypes.', links: [mdn('Web/JavaScript/Reference/Classes')] },
      { title: 'Event loop', description: 'Concorrência no JavaScript.', links: [mdn('Web/JavaScript/Event_loop')] },
    ],
  },
  {
    id: 'typescript',
    name: 'TypeScript',
    category: 'Skill-based',
    description: 'Guia completo de TypeScript.',
    url: 'https://roadmap.sh/typescript',
    items: [
      { title: 'Tipos básicos', description: 'string, number, boolean, array, any.', links: [{ label: 'Handbook', url: 'https://www.typescriptlang.org/docs/handbook/2/everyday-types.html' }] },
      { title: 'Interfaces', description: 'Contratos de forma de objetos.', links: [{ label: 'Interfaces', url: 'https://www.typescriptlang.org/docs/handbook/2/objects.html' }] },
      { title: 'Type aliases', description: 'Nomear tipos.', links: [{ label: 'Handbook', url: 'https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#type-aliases' }] },
      { title: 'Union e intersection', description: 'Combinar tipos.', links: [{ label: 'Unions', url: 'https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#union-types' }] },
      { title: 'Generics', description: 'Tipos parametrizados.', links: [{ label: 'Generics', url: 'https://www.typescriptlang.org/docs/handbook/2/generics.html' }] },
      { title: 'Enums', description: 'Conjuntos de constantes nomeadas.', links: [{ label: 'Enums', url: 'https://www.typescriptlang.org/docs/handbook/enums.html' }] },
      { title: 'Tuplas', description: 'Arrays de tamanho e tipos fixos.' },
      { title: 'Inferência de tipos', description: 'O TS deduz tipos automaticamente.' },
      { title: 'Type narrowing', description: 'Refinar tipos com checagens.', links: [{ label: 'Narrowing', url: 'https://www.typescriptlang.org/docs/handbook/2/narrowing.html' }] },
      { title: 'Type guards', description: 'Funções que refinam tipos.' },
      { title: 'Utility types', description: 'Partial, Pick, Omit, Record.', links: [{ label: 'Utility Types', url: 'https://www.typescriptlang.org/docs/handbook/utility-types.html' }] },
      { title: 'keyof e typeof', description: 'Derivar tipos de valores.' },
      { title: 'Mapped types', description: 'Transformar tipos de objeto.', links: [{ label: 'Mapped Types', url: 'https://www.typescriptlang.org/docs/handbook/2/mapped-types.html' }] },
      { title: 'Conditional types', description: 'Tipos condicionais.', links: [{ label: 'Conditional Types', url: 'https://www.typescriptlang.org/docs/handbook/2/conditional-types.html' }] },
      { title: 'Declaration files (.d.ts)', description: 'Tipagem para libs JS.' },
      { title: 'tsconfig', description: 'Configuração do compilador.', links: [{ label: 'tsconfig', url: 'https://www.typescriptlang.org/tsconfig' }] },
      { title: 'Discriminated unions', description: 'Unions com campo discriminante.' },
    ],
  },
  {
    id: 'python',
    name: 'Python',
    category: 'Skill-based',
    description: 'Fundamentos de Python.',
    url: 'https://roadmap.sh/python',
    items: [
      { title: 'Sintaxe e variáveis', description: 'Indentação, nomes e atribuição.', links: [{ label: 'Python Tutorial', url: 'https://docs.python.org/pt-br/3/tutorial/' }] },
      { title: 'Tipos de dados', description: 'int, float, str, bool.' },
      { title: 'Controle de fluxo', description: 'if, for, while.' },
      { title: 'Funções', description: 'def, argumentos e retorno.', links: [{ label: 'Functions', url: 'https://docs.python.org/pt-br/3/tutorial/controlflow.html#defining-functions' }] },
      { title: 'Listas, tuplas, sets e dicts', description: 'Coleções built-in.', links: [{ label: 'Data Structures', url: 'https://docs.python.org/pt-br/3/tutorial/datastructures.html' }] },
      { title: 'Comprehensions', description: 'List/dict comprehensions.' },
      { title: 'Strings', description: 'Manipulação de texto.' },
      { title: 'Arquivos', description: 'Ler e escrever arquivos.' },
      { title: 'Módulos e pacotes', description: 'Organização de código.', links: [{ label: 'Modules', url: 'https://docs.python.org/pt-br/3/tutorial/modules.html' }] },
      { title: 'pip e venv', description: 'Dependências e ambientes.', links: [{ label: 'venv', url: 'https://docs.python.org/pt-br/3/library/venv.html' }] },
      { title: 'Exceções', description: 'try/except/finally.', links: [{ label: 'Errors', url: 'https://docs.python.org/pt-br/3/tutorial/errors.html' }] },
      { title: 'POO (classes)', description: 'Classes, herança e métodos.', links: [{ label: 'Classes', url: 'https://docs.python.org/pt-br/3/tutorial/classes.html' }] },
      { title: 'Decorators', description: 'Modificar funções/métodos.' },
      { title: 'Generators', description: 'yield e iteradores preguiçosos.' },
      { title: 'Type hints', description: 'Anotações de tipo.', links: [{ label: 'typing', url: 'https://docs.python.org/pt-br/3/library/typing.html' }] },
      { title: 'Testes (pytest)', description: 'Testes automatizados.', links: [{ label: 'pytest', url: 'https://docs.pytest.org/' }] },
      { title: 'Async (asyncio)', description: 'Concorrência assíncrona.', links: [{ label: 'asyncio', url: 'https://docs.python.org/pt-br/3/library/asyncio.html' }] },
      { title: 'Bibliotecas populares', description: 'requests, pandas, numpy.' },
    ],
  },
  {
    id: 'system-design',
    name: 'System Design',
    category: 'Skill-based',
    description: 'Fundamentos de projeto de sistemas escaláveis.',
    url: 'https://roadmap.sh/system-design',
    items: [
      { title: 'Escalabilidade', description: 'Horizontal vs vertical.', links: [{ label: 'System Design Primer', url: 'https://github.com/donnemartin/system-design-primer' }] },
      { title: 'Latência vs throughput', description: 'Métricas de desempenho.' },
      { title: 'Load balancing', description: 'Distribuir carga entre servidores.' },
      { title: 'Cache (Redis, CDN)', description: 'Reduzir latência e carga.' },
      { title: 'SQL vs NoSQL', description: 'Quando usar cada um.' },
      { title: 'Sharding', description: 'Particionar dados horizontalmente.' },
      { title: 'Replicação', description: 'Cópias para disponibilidade.' },
      { title: 'Teorema CAP', description: 'Consistência, disponibilidade, partição.' },
      { title: 'Filas de mensagens (Kafka)', description: 'Comunicação assíncrona.' },
      { title: 'Rate limiting', description: 'Controlar taxa de requisições.' },
      { title: 'Design de APIs', description: 'REST/GraphQL bem projetadas.' },
      { title: 'Microsserviços', description: 'Serviços independentes.' },
      { title: 'Proxy e reverse proxy', description: 'Intermediários de rede.' },
      { title: 'Consistent hashing', description: 'Distribuição estável de dados.' },
      { title: 'Índices e particionamento', description: 'Performance de banco.' },
      { title: 'Disponibilidade e tolerância a falhas', description: 'Sistemas resilientes.' },
    ],
  },
  {
    id: 'docker',
    name: 'Docker',
    category: 'Skill-based',
    description: 'Containers com Docker.',
    url: 'https://roadmap.sh/docker',
    items: [
      { title: 'Containers vs VMs', description: 'Diferenças e vantagens.', links: [{ label: 'Docker overview', url: 'https://docs.docker.com/get-started/docker-overview/' }] },
      { title: 'Imagens', description: 'Templates imutáveis dos containers.' },
      { title: 'Dockerfile', description: 'Receita para construir imagens.', links: [{ label: 'Dockerfile', url: 'https://docs.docker.com/reference/dockerfile/' }] },
      { title: 'Layers e cache', description: 'Camadas e otimização de build.' },
      { title: 'docker build e run', description: 'Construir e executar.' },
      { title: 'Volumes', description: 'Persistir dados.', links: [{ label: 'Volumes', url: 'https://docs.docker.com/engine/storage/volumes/' }] },
      { title: 'Redes', description: 'Comunicação entre containers.' },
      { title: 'Docker Compose', description: 'Multi-container declarativo.', links: [{ label: 'Compose', url: 'https://docs.docker.com/compose/' }] },
      { title: 'Registries', description: 'Docker Hub e privados.' },
      { title: 'Variáveis de ambiente', description: 'Configuração de containers.' },
      { title: 'Multi-stage builds', description: 'Imagens menores.', links: [{ label: 'Multi-stage', url: 'https://docs.docker.com/build/building/multi-stage/' }] },
      { title: 'Health checks', description: 'Verificar saúde do container.' },
      { title: 'Boas práticas e segurança', description: 'Imagens seguras e enxutas.' },
    ],
  },
  {
    id: 'kubernetes',
    name: 'Kubernetes',
    category: 'Skill-based',
    description: 'Orquestração de containers com Kubernetes.',
    url: 'https://roadmap.sh/kubernetes',
    items: [
      { title: 'Pods', description: 'Menor unidade de deploy.', links: [{ label: 'Pods', url: 'https://kubernetes.io/docs/concepts/workloads/pods/' }] },
      { title: 'Nodes e Clusters', description: 'Máquinas e o cluster.' },
      { title: 'Deployments', description: 'Gerenciar réplicas e rollouts.', links: [{ label: 'Deployments', url: 'https://kubernetes.io/docs/concepts/workloads/controllers/deployment/' }] },
      { title: 'ReplicaSets', description: 'Manter N réplicas.' },
      { title: 'Services', description: 'Expor pods de forma estável.', links: [{ label: 'Services', url: 'https://kubernetes.io/docs/concepts/services-networking/service/' }] },
      { title: 'Ingress', description: 'Roteamento HTTP externo.' },
      { title: 'ConfigMaps e Secrets', description: 'Configuração e segredos.' },
      { title: 'Volumes / PVs', description: 'Armazenamento persistente.' },
      { title: 'Namespaces', description: 'Isolamento lógico.' },
      { title: 'kubectl', description: 'CLI do Kubernetes.', links: [{ label: 'kubectl', url: 'https://kubernetes.io/docs/reference/kubectl/' }] },
      { title: 'Helm', description: 'Gerenciador de pacotes.', links: [{ label: 'Helm', url: 'https://helm.sh/docs/' }] },
      { title: 'StatefulSets', description: 'Workloads com estado.' },
      { title: 'Jobs e CronJobs', description: 'Tarefas pontuais e agendadas.' },
      { title: 'Autoscaling (HPA)', description: 'Escalar por métricas.' },
      { title: 'RBAC', description: 'Controle de acesso.' },
    ],
  },
  {
    id: 'sql',
    name: 'SQL / PostgreSQL',
    category: 'Skill-based',
    description: 'Banco de dados relacional e SQL.',
    url: 'https://roadmap.sh/postgresql-dba',
    items: [
      { title: 'SELECT e WHERE', description: 'Consultar e filtrar dados.', links: [{ label: 'PostgreSQL Tutorial', url: 'https://www.postgresql.org/docs/current/tutorial-select.html' }] },
      { title: 'ORDER BY e LIMIT', description: 'Ordenar e limitar resultados.' },
      { title: 'JOINs', description: 'INNER, LEFT, RIGHT, FULL.', links: [{ label: 'Joins', url: 'https://www.postgresql.org/docs/current/tutorial-join.html' }] },
      { title: 'GROUP BY e agregações', description: 'COUNT, SUM, AVG.' },
      { title: 'HAVING', description: 'Filtrar grupos.' },
      { title: 'Subqueries', description: 'Consultas aninhadas.' },
      { title: 'INSERT, UPDATE, DELETE', description: 'Modificar dados.' },
      { title: 'Constraints', description: 'PK, FK, UNIQUE, CHECK.' },
      { title: 'Índices', description: 'Acelerar consultas.', links: [{ label: 'Indexes', url: 'https://www.postgresql.org/docs/current/indexes.html' }] },
      { title: 'Transações e ACID', description: 'Atomicidade e consistência.' },
      { title: 'Views', description: 'Consultas salvas.' },
      { title: 'CTEs (WITH)', description: 'Consultas legíveis e recursivas.' },
      { title: 'Window functions', description: 'Cálculos sobre janelas.', links: [{ label: 'Window Functions', url: 'https://www.postgresql.org/docs/current/tutorial-window.html' }] },
      { title: 'Normalização', description: 'Formas normais e modelagem.' },
      { title: 'EXPLAIN e otimização', description: 'Analisar planos de execução.', links: [{ label: 'EXPLAIN', url: 'https://www.postgresql.org/docs/current/using-explain.html' }] },
    ],
  },
  {
    id: 'git',
    name: 'Git e GitHub',
    category: 'Skill-based',
    description: 'Controle de versão com Git e GitHub.',
    url: 'https://roadmap.sh/git-github',
    items: [
      { title: 'init e clone', description: 'Criar/copiar repositórios.', links: [{ label: 'Pro Git', url: 'https://git-scm.com/book/pt-br/v2' }] },
      { title: 'add e commit', description: 'Registrar mudanças.' },
      { title: 'status e log', description: 'Ver estado e histórico.' },
      { title: 'Branches', description: 'Linhas de desenvolvimento.', links: [{ label: 'Branching', url: 'https://git-scm.com/book/pt-br/v2/Branches-no-Git-Branches-em-poucas-palavras' }] },
      { title: 'Merge', description: 'Unir branches.' },
      { title: 'Rebase', description: 'Reescrever histórico linear.' },
      { title: 'Remotes', description: 'Repositórios remotos.' },
      { title: 'push, pull e fetch', description: 'Sincronizar com o remoto.' },
      { title: '.gitignore', description: 'Ignorar arquivos.' },
      { title: 'Stash', description: 'Guardar mudanças temporariamente.' },
      { title: 'Tags', description: 'Marcar versões.' },
      { title: 'reset e revert', description: 'Desfazer mudanças.' },
      { title: 'Resolução de conflitos', description: 'Resolver merges divergentes.' },
      { title: 'Pull Requests e code review', description: 'Colaboração no GitHub.', links: [{ label: 'GitHub PRs', url: 'https://docs.github.com/pt/pull-requests' }] },
      { title: 'GitHub Actions', description: 'Automação e CI/CD.', links: [{ label: 'Actions', url: 'https://docs.github.com/actions' }] },
    ],
  },
  {
    id: 'dsa',
    name: 'Estruturas de Dados e Algoritmos',
    category: 'Skill-based',
    description: 'DSA para entrevistas e fundamentos.',
    url: 'https://roadmap.sh/datastructures-and-algorithms',
    items: [
      { title: 'Notação Big-O', description: 'Complexidade de tempo e espaço.', links: [{ label: 'Big-O Cheat Sheet', url: 'https://www.bigocheatsheet.com/' }] },
      { title: 'Arrays', description: 'Estrutura contígua indexada.' },
      { title: 'Strings', description: 'Manipulação de texto.' },
      { title: 'Listas ligadas', description: 'Nós encadeados.' },
      { title: 'Pilhas e filas', description: 'LIFO e FIFO.' },
      { title: 'Hash tables', description: 'Mapas com acesso O(1).' },
      { title: 'Árvores (BST)', description: 'Árvores binárias de busca.' },
      { title: 'Heaps', description: 'Filas de prioridade.' },
      { title: 'Grafos', description: 'Nós e arestas.' },
      { title: 'Recursão', description: 'Funções que chamam a si mesmas.' },
      { title: 'Ordenação', description: 'Quick sort, merge sort.' },
      { title: 'Busca binária', description: 'Busca em O(log n).' },
      { title: 'Two pointers', description: 'Técnica de dois ponteiros.' },
      { title: 'Sliding window', description: 'Janela deslizante.' },
      { title: 'BFS e DFS', description: 'Percursos em grafos/árvores.' },
      { title: 'Programação dinâmica', description: 'Memoização e tabulação.' },
      { title: 'Greedy e backtracking', description: 'Estratégias de solução.' },
    ],
  },
  {
    id: 'go',
    name: 'Go',
    category: 'Skill-based',
    description: 'Fundamentos da linguagem Go.',
    url: 'https://roadmap.sh/golang',
    items: [
      { title: 'Sintaxe e variáveis', description: 'Tipos, declarações e pacotes.', links: [{ label: 'A Tour of Go', url: 'https://go.dev/tour/' }] },
      { title: 'Tipos de dados', description: 'Numéricos, strings, booleanos.' },
      { title: 'Funções', description: 'Múltiplos retornos e closures.' },
      { title: 'Pacotes e módulos', description: 'go mod e organização.', links: [{ label: 'Modules', url: 'https://go.dev/doc/modules/managing-dependencies' }] },
      { title: 'Structs', description: 'Tipos compostos.' },
      { title: 'Interfaces', description: 'Polimorfismo implícito.' },
      { title: 'Ponteiros', description: 'Referências de memória.' },
      { title: 'Slices e maps', description: 'Coleções dinâmicas.' },
      { title: 'Goroutines', description: 'Concorrência leve.', links: [{ label: 'Goroutines', url: 'https://go.dev/tour/concurrency/1' }] },
      { title: 'Channels', description: 'Comunicação entre goroutines.' },
      { title: 'sync e WaitGroup', description: 'Sincronização.' },
      { title: 'Tratamento de erros', description: 'error idiomático.' },
      { title: 'defer, panic e recover', description: 'Controle de fluxo.' },
      { title: 'Testes', description: 'Pacote testing.', links: [{ label: 'Testing', url: 'https://go.dev/doc/tutorial/add-a-test' }] },
      { title: 'Servidor HTTP', description: 'net/http.' },
      { title: 'Generics', description: 'Tipos genéricos.' },
    ],
  },
];
